# Site settings
title:            'Hyde + Pixyll'
sidebar_title:    'Hyde <br> + <br> Pixyll'
tagline:          'A Jekyll theme'
description:      'Jekyll theme: <br> Hyde sidebar <br> + <br> Pixyll clean style.'
url:              https://github.com/tranhungnghiep/hyde_pixyll
baseurl:          /

author:
  name:           'Hung-Nghiep Tran'
  email:          tranhungnghiep at g mail
  url:            http://tranhungnghiep.github.io

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/tranhungnghiep/hyde_pixyll

# Build settings
markdown: kramdown
permalink: pretty
paginate: 5
paginate_path: "page:num"

# Gems plugins
plugins: [jekyll-paginate, jekyll-gist]
